# ruff: noqa PLC0415

"""CLI to merge the frame files generated by gwmock simulations."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer


def merge_command(  # pylint: disable=too-many-locals,too-many-branches,too-many-statements
    file_names: Annotated[list[Path], typer.Argument(..., help="List of frame files to merge")],
    channel: Annotated[str, typer.Option("--channel", help="Channel name to merge")] = "STRAIN",
    output: (
        Annotated[
            str,
            typer.Option(
                "--output",
                help=(
                    "Output file name. Its extension selects the format, as everywhere else in gwmock. "
                    "Omit it to write 'merged' in the inputs' own format."
                ),
            ),
        ]
        | None
    ) = None,
    output_channel: (
        Annotated[str, typer.Option("--output-channel", help="Channel name for the output file")] | None
    ) = None,
    metadata: Annotated[list[str], typer.Option("--metadata", help="Metadata file to use for merging")] | None = None,
    author: Annotated[str, typer.Option("--author", help="Author of the merged file")] | None = None,
    email: Annotated[str, typer.Option("--email", help="Email of the author")] | None = None,
    force: Annotated[bool, typer.Option("--force", help="Bypass the requirements of providing metadata files")] = False,
    include_injection_parameters: Annotated[
        bool,
        typer.Option(
            "--include-injection-parameters",
            help=(
                "Embed the source parameters of the injected signals in the merged HDF5 file. Off by "
                "default, matching 'orchestration.include-injection-parameters' in a run's config: a "
                "merge of a blind challenge's frames is still a blind challenge's frames."
            ),
        ),
    ] = False,
):
    """Merge multiple frame files into a single file.

    Args:
        file_names (list[str]): List of frame files to merge.
        channel (str): Channel name to merge.
        output (str | None): Output file name; its extension selects the format. ``None`` infers the
            format from the inputs and writes ``merged`` with that extension.
        output_channel (str | None): Channel name for the output file. If None, use
        metadata (list[str] | None): List of metadata files corresponding to the frame files.
        author (str | None): Author of the merged file.
        email (str | None): Email of the author.
        force (bool): If True, bypass the requirement of providing metadata files.
        include_injection_parameters (bool): If True, the record embedded in the merged HDF5 file
            keeps the source parameters of the injected signals. It is off by default for the reason
            a run's own flag is: the sources' metadata files carry those parameters, so a merge that
            embedded them verbatim would put a blind challenge's answers into the file it releases.

    Raises:
        ValueError: If metadata files are not provided and force is False, or if the format cannot be
            inferred because the inputs do not agree on one.
    """
    import datetime

    output = _resolve_output(output, file_names)

    import getpass
    from typing import cast

    import yaml
    from gwpy.timeseries import TimeSeries

    from gwmock.cli.utils.hash import compute_file_hash
    from gwmock.cli.utils.metadata import embed_metadata_record
    from gwmock.strain_schema import declare_strain_schema
    from gwmock.utils.log import get_dependency_versions

    if file_names is None:
        file_names = []
    if not isinstance(metadata, list) and not force:
        raise ValueError("Metadata files must be provided unless --force is used.")

    if isinstance(metadata, list) and not force:
        typer.echo("Validating files...")

        if len(file_names) != len(metadata or []):
            raise ValueError("The number of metadata files must match the number of frame files.")

        # Validate the files against the metadata
        for i, file_name in enumerate(file_names):
            metadata_file = Path(metadata[i])

            # Find the corresponding metadata entry for the file_name
            with metadata_file.open("r", encoding="utf-8") as f:
                file_metadata = yaml.safe_load(f)

            file_hashes: dict = file_metadata.get("file_hashes", {})
            expected_hash = file_hashes.get(file_name.name)

            if expected_hash is None:
                raise ValueError(f"No hash found in metadata for file {file_name.name}")

            actual_hash = compute_file_hash(file_name)

            if actual_hash != expected_hash:
                raise ValueError(
                    f"Hash mismatch for file {file_name.name}: expected {expected_hash}, got {actual_hash}"
                )

    # Placeholder for actual merging logic
    typer.echo(f"Merging files: {file_names}")

    # Read the first file
    frame_data = cast(TimeSeries, TimeSeries.read(file_names[0], channel))

    # Get the start time, duration and sampling frequency
    start_time = frame_data.epoch
    duration = frame_data.duration
    sampling_frequency = frame_data.sample_rate

    for i in range(1, len(file_names)):
        next_frame_data = cast(TimeSeries, TimeSeries.read(file_names[i], channel))

        if next_frame_data.epoch != start_time:
            raise ValueError(f"Start time mismatch: {next_frame_data.epoch} != {start_time}")
        if next_frame_data.duration != duration:
            raise ValueError(f"Duration mismatch: {next_frame_data.duration} != {duration}")
        if next_frame_data.sample_rate != sampling_frequency:
            raise ValueError(f"Sampling frequency mismatch: {next_frame_data.sample_rate} != {sampling_frequency}")

        frame_data = frame_data.inject(next_frame_data)

    # Write the merged data to a new file
    # Atomic write to avoid partial writes
    # The write function is suffix sensitive, so we prepend a .tmp to the original suffix
    temp_output = Path(output).with_suffix(".tmp" + Path(output).suffix)
    if output_channel is not None:
        # Both, because they are read by different things. gwpy's frame writer takes the channel
        # name in the output file from `name`; `channel` carries the metadata a later reader sees
        # attached to the series. Setting only `channel` -- which is what this did -- left the file
        # holding the *input* channel name, so `--output-channel` renamed nothing.
        frame_data.channel = output_channel
        frame_data.name = output_channel
    frame_data.write(temp_output)
    # Declared before the rename, so the merged file carries the contract from the moment it appears
    # under its final name -- a reader that opens it the instant it exists sees a complete artifact.
    # A merge is a strain artifact like any other, and it is the one gwmock hands to another pipeline.
    declare_strain_schema(temp_output)

    merged_metadata: dict | None = None
    if metadata:
        merged_metadata = {"type": "merged", "source_files": {}}

        for i, file_name in enumerate(file_names):
            metadata_file = Path(metadata[i])

            with metadata_file.open("r", encoding="utf-8") as f:
                file_metadata = yaml.safe_load(f)

            # Keyed by the path as a string: `file_names` holds `Path` objects, and `safe_dump`
            # has no representer for one, so a `Path` key made the dump below raise
            # `RepresenterError` -- every merge that was given metadata (that is, every merge not
            # forced past the check above) failed after writing the merged frame.
            merged_metadata["source_files"][str(file_name)] = file_metadata

        if author is None:
            author = getpass.getuser()

        timestamp = datetime.datetime.now(datetime.timezone.utc)

        merged_metadata["output_files"] = [output]
        merged_metadata["author"] = author
        merged_metadata["email"] = email
        merged_metadata["timestamp"] = timestamp.isoformat()
        merged_metadata["versions"] = get_dependency_versions()

        # Embedded here for the two reasons the declaration above is placed here: before the rename,
        # so the file is complete the moment it appears under its final name, and before the hash
        # below, since embedding changes the container bytes the hash is of. The sources' records
        # are copied in whole, so they bring their injection parameters with them -- which is why
        # this goes through the same withholding as a run's own outputs rather than writing the
        # document as assembled.
        embed_metadata_record(
            temp_output,
            merged_metadata,
            include_injection_parameters=include_injection_parameters,
        )

    temp_output.rename(output)

    if merged_metadata is not None:
        # If metadata is provided, create a new metadata file for the merged file

        typer.echo("Creating merged metadata file...")

        merged_metadata["file_hashes"] = {output: compute_file_hash(output)}

        # Atomic write of metadata file
        merged_metadata_file = Path(output).with_suffix(".metadata.yaml")
        temp_metadata_file = merged_metadata_file.with_suffix(".tmp")
        with temp_metadata_file.open("w", encoding="utf-8") as f:
            yaml.safe_dump(merged_metadata, f)
        temp_metadata_file.rename(merged_metadata_file)

        typer.echo(f"Merged metadata file created at {merged_metadata_file}")

    else:
        typer.echo("No metadata provided for the source files.")
        typer.echo("No metadata file will be created for the merged file.")


def _resolve_output(output: str | None, file_names: list[Path]) -> str:
    """Return the output path, inferring the format from the inputs when none was given.

    gwmock selects a format by file extension rather than by a flag, so ``--output`` carries the choice
    and this only supplies a default. The default follows the inputs instead of a fixed format: merging
    GWF frames for a pipeline that reads GWF should not quietly hand back HDF5 because HDF5 is what a run
    writes now.

    Mixed inputs raise rather than picking one. Merging a GWF and an HDF5 file is a coherent request with
    two defensible answers, and guessing would silently drop half the caller's intent -- naming both
    formats and asking for ``--output`` costs one line and cannot be wrong.

    Args:
        output: The ``--output`` value, or ``None``.
        file_names: The inputs being merged.

    Returns:
        The output file name.

    Raises:
        ValueError: If no output was given and the inputs do not agree on a format.
    """
    if output is not None:
        return output
    suffixes = sorted({Path(name).suffix.lower() for name in file_names if Path(name).suffix})
    if not suffixes:
        raise ValueError(
            "Cannot infer the output format: none of the input files has an extension. "
            "Pass --output with the extension you want, for example --output merged.hdf5."
        )
    if len(suffixes) > 1:
        raise ValueError(
            f"Cannot infer the output format: the inputs are a mixture of {', '.join(suffixes)}. "
            f"Pass --output with the extension you want, for example --output merged{suffixes[0]}."
        )
    return f"merged{suffixes[0]}"
